# Generated by Django 6.0.4 on 2026-05-04 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfCategories',
            fields=[
                ('id_list_of_categories', models.AutoField(db_column='id_list_of_categories', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Lists of categories',
                'db_table': 'list_of_categories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(db_column='id_order', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'card'), ('cash', 'cash'), ('paypal', 'paypal'), ('klarna', 'klarna')], max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('created', 'created'), ('payed', 'payed'), ('packaging', 'packaging'), ('shipped', 'shipped'), ('in_transit', 'in_transit'), ('delivery', 'delivery'), ('delivered', 'delivered')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='ShopUser',
            fields=[
                ('id_user', models.AutoField(db_column='id_user', primary_key=True, serialize=False)),
                ('surname', models.CharField(blank=True, max_length=25, null=True)),
                ('lastname', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('photo', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(db_column='id_category', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('list_of_categories', models.ForeignKey(db_column='list_of_categories_id', on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='shop.listofcategories')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(db_column='id_product', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id_order_item', models.AutoField(db_column='id_order_item', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.product')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id_inventory', models.AutoField(db_column='id_inventory', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='shop.product')),
            ],
            options={
                'verbose_name_plural': 'Inventory',
                'db_table': 'inventory',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.shopuser'),
        ),
    ]
