# Generated by Django 6.0.4 on 2026-05-04 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='list_of_categories',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='shop.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ListOfCategories',
        ),
    ]
