# Generated by Django 6.0.4 on 2026-05-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_category_list_of_categories_category_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
        migrations.AlterModelTable(
            name='order',
            table='shop_order',
        ),
        migrations.AlterModelTable(
            name='shopuser',
            table='shop_user',
        ),
    ]
